name: Publish to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Increment version
      run: node scripts/increment-version.js

    - name: Zip the code directory
      run: zip -r code.zip code/

    - name: Publish to Chrome Web Store
      uses: GoogleChromeLabs/chrome-webstore-upload-cli@v1
      with:
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        asset: './code.zip'